live_config_reload = true

# [colors.cursor]
# cursor = "0x5c6370"
# text = "0x2c323c"
#
# [colors.normal]
# black = "0x2c323c"
# blue = "0x61afef"
# cyan = "0x56b6c2"
# green = "0x98c379"
# magenta = "0xc678dd"
# red = "0xe06c75"
# white = "0x5c6370"
# yellow = "0xe5c07b"
#
# [colors.primary]
# background = "0x282c34"
# foreground = "0xabb2bf"
#
# [colors.selection]
# background = "0x3e4452"
# text = "CellForeground"

import = [
  # "./catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-latte.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

# [keyboard]
# bindings = [
# { key = ",", mods = "Command", chars = "\u0001," },
# ]

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"
# draw_bold_text_with_bright_colors = true

[window.padding]
x = 0
y = 0

