live_config_reload = true

[colors.cursor]
cursor = "0x5c6370"
text = "0x2c323c"

[colors.normal]
black = "0x2c323c"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x5c6370"
yellow = "0xe5c07b"

[colors.primary]
background = "0x282c34"
foreground = "0xabb2bf"

[colors.selection]
background = "0x3e4452"
text = "CellForeground"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[keyboard]
bindings = [
{ key = "A", mods = "Alt", chars = "\u001Ba" },
{ key = "B", mods = "Alt", chars = "\u001Bb" },
{ key = "C", mods = "Alt", chars = "\u001Bc" },
{ key = "D", mods = "Alt", chars = "\u001Bd" },
{ key = "E", mods = "Alt", chars = "\u001Be" },
{ key = "F", mods = "Alt", chars = "\u001Bf" },
{ key = "G", mods = "Alt", chars = "\u001Bg" },
{ key = "H", mods = "Alt", chars = "\u001Bh" },
{ key = "I", mods = "Alt", chars = "\u001Bi" },
{ key = "J", mods = "Alt", chars = "\u001Bj" },
{ key = "K", mods = "Alt", chars = "\u001Bk" },
{ key = "L", mods = "Alt", chars = "\u001Bl" },
{ key = "M", mods = "Alt", chars = "\u001Bm" },
{ key = "N", mods = "Alt", chars = "\u001Bn" },
{ key = "O", mods = "Alt", chars = "\u001Bo" },
{ key = "P", mods = "Alt", chars = "\u001Bp" },
{ key = "Q", mods = "Alt", chars = "\u001Bq" },
{ key = "R", mods = "Alt", chars = "\u001Br" },
{ key = "S", mods = "Alt", chars = "\u001Bs" },
{ key = "T", mods = "Alt", chars = "\u001Bt" },
{ key = "U", mods = "Alt", chars = "\u001Bu" },
{ key = "V", mods = "Alt", chars = "\u001Bv" },
{ key = "W", mods = "Alt", chars = "\u001Bw" },
{ key = "X", mods = "Alt", chars = "\u001Bx" },
{ key = "Y", mods = "Alt", chars = "\u001By" },
{ key = "Z", mods = "Alt", chars = "\u001Bz" },
{ key = "A", mods = "Alt|Shift", chars = "\u001BA" },
{ key = "B", mods = "Alt|Shift", chars = "\u001BB" },
{ key = "C", mods = "Alt|Shift", chars = "\u001BC" },
{ key = "D", mods = "Alt|Shift", chars = "\u001BD" },
{ key = "E", mods = "Alt|Shift", chars = "\u001BE" },
{ key = "F", mods = "Alt|Shift", chars = "\u001BF" },
{ key = "G", mods = "Alt|Shift", chars = "\u001BG" },
{ key = "H", mods = "Alt|Shift", chars = "\u001BH" },
{ key = "I", mods = "Alt|Shift", chars = "\u001BI" },
{ key = "J", mods = "Alt|Shift", chars = "\u001BJ" },
{ key = "K", mods = "Alt|Shift", chars = "\u001BK" },
{ key = "L", mods = "Alt|Shift", chars = "\u001BL" },
{ key = "M", mods = "Alt|Shift", chars = "\u001BM" },
{ key = "N", mods = "Alt|Shift", chars = "\u001BN" },
{ key = "O", mods = "Alt|Shift", chars = "\u001BO" },
{ key = "P", mods = "Alt|Shift", chars = "\u001BP" },
{ key = "Q", mods = "Alt|Shift", chars = "\u001BQ" },
{ key = "R", mods = "Alt|Shift", chars = "\u001BR" },
{ key = "S", mods = "Alt|Shift", chars = "\u001BS" },
{ key = "T", mods = "Alt|Shift", chars = "\u001BT" },
{ key = "U", mods = "Alt|Shift", chars = "\u001BU" },
{ key = "V", mods = "Alt|Shift", chars = "\u001BV" },
{ key = "W", mods = "Alt|Shift", chars = "\u001BW" },
{ key = "X", mods = "Alt|Shift", chars = "\u001BX" },
{ key = "Y", mods = "Alt|Shift", chars = "\u001BY" },
{ key = "Z", mods = "Alt|Shift", chars = "\u001BZ" },
]

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"
# draw_bold_text_with_bright_colors = true

[window.padding]
x = 0
y = 0

